---
# this comment is a also hack
version: '3'
services:
  ombi:
    image: linuxserver/ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
